virtualenv:
  system_site_packages: true
language: python
python:
#  - "2.6"
  - "3.5"
# command to install dependencies
install: python setup.py install
install: pip install -r requirements.txt
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3-numpy python3-scipy python3-biopython
# command to run tests
script: python biskit/test.py
