#virtualenv:
#  system_site_packages: true
language: python
python:
#  - "2.7"
#  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: pip install -r requirements_extended.txt
# install: python setup.py install
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y plotutils libplot-dev python-dev libblas-dev liblapack-dev gfortran
# command to run tests
script: coverage python biskit/test.py
after_success: coverage-badge -o coverage.svg
