sudo: required

language: python
python:
  - "3.6"

services:
  - docker

# command to install dependencies
before_install:
  - docker build -t graik/biskit .

install:
  - pip install coverage coveralls
  
# command to run tests
script:
  docker run -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" \
             -e TRAVIS_BRANCH="$TRAVIS_BRANCH" \
             -v "$PWD:/app" \
             -t graik/biskit \
             coverage run biskit/test.py -e fails old extra
after_success:
  coveralls
after_failure:
  coveralls