language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
# install: pip install -r requirements.txt
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-numpy python-scipy python-biopython python-pybiggles
# command to run tests
script: python Biskit/test.py -e pvm old exe
