virtualenv:
  system_site_packages: true
language: python
dist: precise
python:
  - "2.7"
# command to install dependencies
install: python setup.py install
# install: pip install -r requirements.txt
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-numpy python-scipy python-biopython python-pybiggles
# command to run tests
script: python Biskit/test.py -e pvm old exe
