sudo: required

services:
  - docker

# command to install dependencies
before_install:
  - docker build -t graik/biskit .
  
# command to run tests
script:
  docker run -t graik/biskit coverage run biskit/test.py -e fails old extra
after_success:
  coveralls
after_failure:
  coveralls