virtualenv:
  system_site_packages: true
language: python
python:
#  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: python setup.py install
install: pip install -r requirements_extended.txt
#before_install:
#  - sudo apt-get -qq update
#  - sudo apt-get install -y python3-numpy python3-scipy python3-biopython
# command to run tests
script: coverage python biskit/test.py
after_success: coverage-badge -o coverage.svg
